"""empty message

Revision ID: 12a29fb39382
Revises: 37808cc41c48
Create Date: 2019-03-16 21:16:54.718644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a29fb39382'
down_revision = '37808cc41c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('release_info_url', sa.String(), nullable=True),
    sa.Column('xpath_version_number', sa.String(), nullable=True),
    sa.Column('xpath_download_url', sa.String(), nullable=True),
    sa.Column('newest_version_number', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('release_info')
    # ### end Alembic commands ###
