DT_STR_FORMAT = '%m/%d/%y %I:%M:%S %p %Z'
DT_STR_FORMAT_ALL = '%Y-%m-%d %H:%M:%S.%f %Z%z'
DT_STR_FORMAT_NAIVE = '%m/%d/%y %I:%M:%S %p'
DT_FORMAT_SHORT = '%I:%M:%S %p %Z'
DT_FORMAT_XML = '%m-%d-%y_%H:%M:%S'
DT_FORMAT_ISO = '%Y-%m-%dT%H:%M:%S.%f%z'
MONTH_NAME_SHORT = '%b %d %Y'